name: Generate PDF

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change absolute paths to relative
        run: perl -pi -e 's@\]\(\/@\]\(@' _sidebar.md

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uploader
        run: npm install @iomeg/zenodo-upload

      - name: Pull Docker image
        run: docker pull ghcr.io/kernoeb/docker-docsify-pdf:latest

      - name: Pull Docker image
        run: |
          pwd
          echo "${{ github.workspace }}/"
          tree "${{ github.workspace }}/"

      - name: Generate PDF using the Docker image
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/":/home/node/docs:ro \
            -v "${{ github.workspace }}/":/home/node/pdf:rw \
            -v "${{ github.workspace }}/images/SoftDevGuide-cover.pdf":/home/node/resources/cover.pdf:ro \
            -e "PDF_OUTPUT_NAME=guide-nlesc.pdf" \
            ghcr.io/kernoeb/docker-docsify-pdf:latest

      - name: Adjust permissions on generated PDF
        run: sudo chown $USER:$GROUPS guide-nlesc.pdf

      - name: Upload PDF to Zenodo
        run: npx --package @iomeg/zenodo-upload zenodo_upload 138987 guide-nlesc.pdf "${{ github.ref_name }}" ${{ secrets.ZENODO_TOKEN }}
