name: Generate PDF-simple

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uploader
        run: npm install @iomeg/zenodo-upload

      - name: Upload PDF to Zenodo
        run: npx --package @iomeg/zenodo-upload zenodo_upload --sandbox 139404 guide-nlesc.pdf v1.3 ${{ secrets.ZENODO_TOKEN }}

